In [1]:
import pandas as pd

In [10]:
sales = pd.read_csv("Book1.csv")

In [11]:
sales

,OrderID,Date,Region,SalesPerson,Product,Quantity,UnitPrice,Discount,TotalAmount,Category
0,101,1/10/2024,North,Rahul Sharma,Laptop,2,55000,0.10,99000,Electronics
1,102,1/12/2024,South,Priya Mehta,Keyboard,5,1200,0.05,5700,Accessories
2,103,1/14/2024,West,Anil Verma,Mouse,10,700,0.00,7000,Accessories
3,104,1/18/2024,East,Riya Patel,Monitor,3,15000,0.10,40500,Electronics
4,105,1/20/2024,North,Rahul Sharma,Laptop,1,55000,0.00,55000,Electronics
5,106,1/22/2024,South,Priya Mehta,Mouse,15,700,0.10,9450,Accessories
6,107,1/25/2024,West,Anil Verma,Monitor,2,15000,0.05,28500,Electronics
7,108,2/1/2024,East,Riya Patel,Laptop,3,55000,0.10,148500,Electronics
8,109,2/3/2024,North,Rahul Sharma,Mouse,20,700,0.10,12600,Accessories
9,110,2/7/2024,South,Priya Mehta,Laptop,2,55000,0.00,110000,Electronics
10,111,2/8/2024,West,Anil Verma,Keyboard,10,1200,0.10,10800,Accessories
11,112,2/9/2024,East,Riya Patel,Monitor,1,15000,0.00,15000,Electronics
12,113,2/15/2024,North,Rahul Sharma,Keyboard,8,1200,0.05,9120,Accessories
13,114,2/16/2024,South,Priya Mehta,Mouse,10,700,0.00,7000,Accessories
14,115,2/17/2024,West,Anil Verma,Laptop,4,55000,0.10,198000,Electronics
15,116,2/20/2024,East,Riya Patel,Keyboard,7,1200,0.05,7980,Accessories
16,117,2/22/2024,North,Rahul Sharma,Monitor,2,15000,0.00,30000,Electronics
17,118,2/25/2024,South,Priya Mehta,Laptop,5,55000,0.10,247500,Electronics
18,119,2/28/2024,West,Anil Verma,Mouse,5,700,0.00,3500,Accessories
19,120,3/1/2024,East,Riya Patel,Keyboard,6,1200,0.10,6480,Accessories

In [13]:
sales.rename(columns = {"SalesPerson": "SalesMan"}, inplace= True)

In [14]:
sales

,OrderID,Date,Region,SalesMan,Product,Quantity,UnitPrice,Discount,TotalAmount,Category
0,101,1/10/2024,North,Rahul Sharma,Laptop,2,55000,0.10,99000,Electronics
1,102,1/12/2024,South,Priya Mehta,Keyboard,5,1200,0.05,5700,Accessories
2,103,1/14/2024,West,Anil Verma,Mouse,10,700,0.00,7000,Accessories
3,104,1/18/2024,East,Riya Patel,Monitor,3,15000,0.10,40500,Electronics
4,105,1/20/2024,North,Rahul Sharma,Laptop,1,55000,0.00,55000,Electronics
5,106,1/22/2024,South,Priya Mehta,Mouse,15,700,0.10,9450,Accessories
6,107,1/25/2024,West,Anil Verma,Monitor,2,15000,0.05,28500,Electronics
7,108,2/1/2024,East,Riya Patel,Laptop,3,55000,0.10,148500,Electronics
8,109,2/3/2024,North,Rahul Sharma,Mouse,20,700,0.10,12600,Accessories
9,110,2/7/2024,South,Priya Mehta,Laptop,2,55000,0.00,110000,Electronics
10,111,2/8/2024,West,Anil Verma,Keyboard,10,1200,0.10,10800,Accessories
11,112,2/9/2024,East,Riya Patel,Monitor,1,15000,0.00,15000,Electronics
12,113,2/15/2024,North,Rahul Sharma,Keyboard,8,1200,0.05,9120,Accessories
13,114,2/16/2024,South,Priya Mehta,Mouse,10,700,0.00,7000,Accessories
14,115,2/17/2024,West,Anil Verma,Laptop,4,55000,0.10,198000,Electronics
15,116,2/20/2024,East,Riya Patel,Keyboard,7,1200,0.05,7980,Accessories
16,117,2/22/2024,North,Rahul Sharma,Monitor,2,15000,0.00,30000,Electronics
17,118,2/25/2024,South,Priya Mehta,Laptop,5,55000,0.10,247500,Electronics
18,119,2/28/2024,West,Anil Verma,Mouse,5,700,0.00,3500,Accessories
19,120,3/1/2024,East,Riya Patel,Keyboard,6,1200,0.10,6480,Accessories

In [17]:
sales.replace({"North": "N", "South": "S", "East": "E", "West": "W"}, inplace = True)

In [18]:
sales

,OrderID,Date,Region,SalesMan,Product,Quantity,UnitPrice,Discount,TotalAmount,Category
0,101,1/10/2024,N,Rahul Sharma,Laptop,2,55000,0.10,99000,Electronics
1,102,1/12/2024,S,Priya Mehta,Keyboard,5,1200,0.05,5700,Accessories
2,103,1/14/2024,W,Anil Verma,Mouse,10,700,0.00,7000,Accessories
3,104,1/18/2024,E,Riya Patel,Monitor,3,15000,0.10,40500,Electronics
4,105,1/20/2024,N,Rahul Sharma,Laptop,1,55000,0.00,55000,Electronics
5,106,1/22/2024,S,Priya Mehta,Mouse,15,700,0.10,9450,Accessories
6,107,1/25/2024,W,Anil Verma,Monitor,2,15000,0.05,28500,Electronics
7,108,2/1/2024,E,Riya Patel,Laptop,3,55000,0.10,148500,Electronics
8,109,2/3/2024,N,Rahul Sharma,Mouse,20,700,0.10,12600,Accessories
9,110,2/7/2024,S,Priya Mehta,Laptop,2,55000,0.00,110000,Electronics
10,111,2/8/2024,W,Anil Verma,Keyboard,10,1200,0.10,10800,Accessories
11,112,2/9/2024,E,Riya Patel,Monitor,1,15000,0.00,15000,Electronics
12,113,2/15/2024,N,Rahul Sharma,Keyboard,8,1200,0.05,9120,Accessories
13,114,2/16/2024,S,Priya Mehta,Mouse,10,700,0.00,7000,Accessories
14,115,2/17/2024,W,Anil Verma,Laptop,4,55000,0.10,198000,Electronics
15,116,2/20/2024,E,Riya Patel,Keyboard,7,1200,0.05,7980,Accessories
16,117,2/22/2024,N,Rahul Sharma,Monitor,2,15000,0.00,30000,Electronics
17,118,2/25/2024,S,Priya Mehta,Laptop,5,55000,0.10,247500,Electronics
18,119,2/28/2024,W,Anil Verma,Mouse,5,700,0.00,3500,Accessories
19,120,3/1/2024,E,Riya Patel,Keyboard,6,1200,0.10,6480,Accessories

In [23]:
sales.loc[0:5, ['SalesMan', 'Quantity', 'UnitPrice']]

       SalesMan  Quantity  UnitPrice
0  Rahul Sharma         2      55000
1   Priya Mehta         5       1200
2    Anil Verma        10        700
3    Riya Patel         3      15000
4  Rahul Sharma         1      55000
5   Priya Mehta        15        700

In [22]:
sales.iloc[0:6, 3:6]

       SalesMan   Product  Quantity
0  Rahul Sharma    Laptop         2
1   Priya Mehta  Keyboard         5
2    Anil Verma     Mouse        10
3    Riya Patel   Monitor         3
4  Rahul Sharma    Laptop         1
5   Priya Mehta     Mouse        15

In [32]:
sales.loc[sales['Quantity'] > 5, 'Quantity'] = 10

In [33]:
sales

,OrderID,Date,Region,SalesMan,Product,Quantity,UnitPrice,Discount,TotalAmount,Category
0,101,1/10/2024,N,Rahul Sharma,Laptop,5,55000,0.10,99000,Electronics
1,102,1/12/2024,S,Priya Mehta,Keyboard,5,1200,0.05,5700,Accessories
2,103,1/14/2024,W,Anil Verma,Mouse,10,700,0.00,7000,Accessories
3,104,1/18/2024,E,Riya Patel,Monitor,5,15000,0.10,40500,Electronics
4,105,1/20/2024,N,Rahul Sharma,Laptop,5,55000,0.00,55000,Electronics
5,106,1/22/2024,S,Priya Mehta,Mouse,10,700,0.10,9450,Accessories
6,107,1/25/2024,W,Anil Verma,Monitor,5,15000,0.05,28500,Electronics
7,108,2/1/2024,E,Riya Patel,Laptop,5,55000,0.10,148500,Electronics
8,109,2/3/2024,N,Rahul Sharma,Mouse,10,700,0.10,12600,Accessories
9,110,2/7/2024,S,Priya Mehta,Laptop,5,55000,0.00,110000,Electronics
10,111,2/8/2024,W,Anil Verma,Keyboard,10,1200,0.10,10800,Accessories
11,112,2/9/2024,E,Riya Patel,Monitor,5,15000,0.00,15000,Electronics
12,113,2/15/2024,N,Rahul Sharma,Keyboard,10,1200,0.05,9120,Accessories
13,114,2/16/2024,S,Priya Mehta,Mouse,10,700,0.00,7000,Accessories
14,115,2/17/2024,W,Anil Verma,Laptop,5,55000,0.10,198000,Electronics
15,116,2/20/2024,E,Riya Patel,Keyboard,10,1200,0.05,7980,Accessories
16,117,2/22/2024,N,Rahul Sharma,Monitor,5,15000,0.00,30000,Electronics
17,118,2/25/2024,S,Priya Mehta,Laptop,5,55000,0.10,247500,Electronics
18,119,2/28/2024,W,Anil Verma,Mouse,5,700,0.00,3500,Accessories
19,120,3/1/2024,E,Riya Patel,Keyboard,10,1200,0.10,6480,Accessories