In [2]:
import pandas as pd

1. Series

In [3]:
s = pd.Series(["a","b","c","d","e"], index = [1,2,3,4,5])

In [4]:
type(s)

pandas.core.series.Series

In [5]:
s

1    a
2    b
3    c
4    d
5    e
dtype: object

In [6]:
s2 = pd.Series({1:12, 2:34, 3:45, 4:32})

In [7]:
type(s2)

pandas.core.series.Series

In [8]:
s2

1    12
2    34
3    45
4    32
dtype: int64

In [9]:
s3 = pd.Series([3.14, 2.17], name = "constants")

In [10]:
s3

0    3.14
1    2.17
Name: constants, dtype: float64

2. DataFrame

In [11]:
d = pd.DataFrame({
    "Id" : [1, 2, 3, 4],
    "Name" : ["Juhi", "Aryan", "Nisha", "Sara"]
})

In [12]:
d

   Id   Name
0   1   Juhi
1   2  Aryan
2   3  Nisha
3   4   Sara

In [13]:
df = pd.read_csv("employees.csv")

In [14]:
df

,EEID,Job Title,Department,Business Unit,Gender,Ethnicity,Age,Hire Date,Annual Salary,Bonus %,Country,City,Exit Date
0,E93810,Technical Architect,IT,Speciality Products,Male,Asian,30,30-11-2016,143105.97,0.20,United States,Miami,NaN
1,E13905,Technical Architect,Finance,Manufacturing,Male,Asian,63,12-12-1998,138185.50,0.15,Canada,Vancouver,NaN
2,E10851,Director,Marketing,Corporate,Female,Caucasian,31,04-01-1996,70143.93,0.10,United States,New York,NaN
3,E57052,Account Representative,Operations,Speciality Products,Male,Hispanic,56,22-05-2020,57475.66,0.15,United States,Miami,23-09-2022
4,E92397,Account Representative,Operations,Manufacturing,Male,Black,64,29-06-2003,71905.76,0.10,United States,Seattle,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,E94465,Analyst,HR,Manufacturing,Male,Asian,61,22-01-2008,76127.39,0.10,India,Mumbai,NaN
496,E97186,Account Representative,Sales,Corporate,Female,Black,26,16-03-2018,106546.81,0.10,India,Bangalore,NaN
497,E46996,Account Representative,Operations,Manufacturing,Male,Hispanic,28,12-08-2020,85621.76,0.00,Australia,Melbourne,NaN
498,E62535,Manager,Finance,Manufacturing,Male,Hispanic,46,29-01-2001,49248.39,0.05,Australia,Melbourne,NaN
499,E67062,Account Representative,Operations,Manufacturing,Male,Black,58,07-02-2016,157144.75,0.00,Germany,Munich,NaN

In [15]:
df[df["Age"] <25]

,EEID,Job Title,Department,Business Unit,Gender,Ethnicity,Age,Hire Date,Annual Salary,Bonus %,Country,City,Exit Date
16,E10942,Technical Architect,Marketing,Research & Development,Male,Black,24,07-05-1998,160348.96,0.00,Germany,Berlin,14-10-2005
29,E29536,Sr. Manager,Sales,Manufacturing,Female,Asian,24,30-11-2018,83156.17,0.00,China,Beijing,NaN
39,E40784,Sr. Analyst,Finance,Manufacturing,Male,Black,24,30-12-2023,74277.96,0.15,Germany,Berlin,NaN
49,E59692,Sr. Analyst,HR,Speciality Products,Male,Hispanic,23,03-11-1997,144863.40,0.00,China,Beijing,NaN
61,E35443,Sr. Analyst,Finance,Speciality Products,Male,Caucasian,22,15-11-1997,139122.59,0.05,China,Beijing,NaN
62,E82529,Sr. Analyst,Marketing,Manufacturing,Female,Black,22,05-04-2024,120368.99,0.15,India,Bangalore,NaN
66,E30517,Sr. Manager,HR,Corporate,Female,Caucasian,24,04-02-2008,72406.67,0.10,UK,Manchester,20-07-2017
74,E81987,Director,Sales,Corporate,Female,Black,23,29-03-2004,176240.55,0.20,Australia,Sydney,NaN
80,E87356,Account Representative,IT,Corporate,Male,Hispanic,22,02-05-2013,141142.14,0.15,Australia,Sydney,01-07-2017
113,E37686,Director,Sales,Speciality Products,Female,Black,22,02-04-1998,109633.95,0.15,Canada,Toronto,NaN
114,E40161,Account Representative,IT,Corporate,Male,Hispanic,23,15-11-2020,104365.60,0.00,Australia,Melbourne,NaN
125,E59372,Account Representative,Finance,Research & Development,Female,Caucasian,23,22-02-2008,90763.67,0.05,Canada,Vancouver,NaN
143,E65851,Director,Marketing,Corporate,Female,Hispanic,24,11-03-2012,141754.02,0.10,Germany,Munich,25-02-2025
144,E17518,Technical Architect,Marketing,Corporate,Female,Asian,23,28-03-2001,59989.13,0.20,UK,Manchester,06-07-2018
172,E81197,Manager,HR,Speciality Products,Male,Caucasian,24,14-04-2013,80268.25,0.00,China,Shanghai,NaN
187,E55158,Technical Architect,Operations,Research & Development,Male,Hispanic,24,25-09-2008,80192.70,0.05,Australia,Sydney,NaN
189,E80419,Manager,Operations,Manufacturing,Male,Black,23,12-11-2007,176988.70,0.15,UK,Manchester,NaN
200,E58589,Account Representative,HR,Research & Development,Male,Asian,23,26-08-2002,76508.38,0.20,Germany,Munich,23-11-2002
209,E19744,Sr. Analyst,Operations,Research & Development,Male,Caucasian,23,04-04-2003,174605.69,0.20,Canada,Vancouver,NaN
227,E69303,Account Representative,IT,Speciality Products,Male,Black,23,20-03-2007,158885.20,0.00,UK,London,NaN
258,E43980,Director,Sales,Manufacturing,Female,Black,23,18-10-2020,86901.54,0.15,China,Chongqing,22-10-2022
274,E16637,Director,Operations,Corporate,Female,Hispanic,23,05-09-2017,93582.12,0.15,Canada,Vancouver,16-10-2023
296,E72236,Computer Systems Manager,HR,Speciality Products,Male,Hispanic,24,28-05-2015,110294.21,0.20,Australia,Sydney,23-07-2016
297,E68856,Director,Finance,Manufacturing,Male,Asian,24,18-02-2018,99272.49,0.15,Canada,Toronto,NaN
319,E72573,Manager,IT,Research & Development,Male,Caucasian,22,14-02-2017,164880.89,0.20,Canada,Toronto,NaN
333,E63907,Analyst,IT,Research & Development,Female,Caucasian,22,28-01-2025,138639.54,0.20,Australia,Sydney,NaN
357,E47070,Sr. Manager,Operations,Speciality Products,Female,Hispanic,24,29-09-2004,81500.76,0.05,China,Chongqing,29-11-2011
363,E61248,Sr. Analyst,Marketing,Manufacturing,Female,Caucasian,22,13-10-2011,117493.39,0.20,Canada,Toronto,20-01-2016
402,E61605,Director,HR,Research & Development,Female,Caucasian,22,02-12-2024,41654.80,0.05,India,Delhi,10-01-2025
414,E47247,Analyst,Marketing,Manufacturing,Male,Asian,23,15-06-2022,44921.70,0.10,Australia,Melbourne,NaN
435,E78920,Sr. Analyst,IT,Speciality Products,Male,Black,22,13-08-2017,170229.55,0.05,UK,Manchester,NaN
442,E38157,Account Representative,IT,Speciality Products,Male,Black,24,21-06-2021,104451.77,0.05,Canada,Vancouver,NaN
456,E73525,Technical Architect,Finance,Manufacturing,Female,Black,24,11-12-2009,74634.90,0.20,China,Shanghai,NaN
476,E31146,Sr. Analyst,Operations,Manufacturing,Female,Caucasian,24,31-10-2009,53037.68,0.10,China,Shanghai,NaN
481,E64346,Manager,IT,Speciality Products,Female,Asian,22,03-11-2005,129686.56,0.10,China,Beijing,NaN
489,E14791,Analyst,HR,Research & Development,Male,Caucasian,24,06-11-2008,136187.33,0.20,Australia,Sydney,NaN

In [16]:
df.describe()

              Age  Annual Salary     Bonus %
count  500.000000      500.00000  500.000000
mean    44.050000   109228.28380    0.098400
std     13.060346    39933.49392    0.072719
min     22.000000    40219.01000    0.000000
25%     32.000000    74583.99500    0.050000
50%     45.000000   108325.72500    0.100000
75%     56.000000   143233.04500    0.150000
max     65.000000   179912.30000    0.200000

In [17]:
b = df[df["Age"] <25]

In [18]:
b.shape

(36, 13)

In [19]:
df.shape

(500, 13)

In [20]:
df[0:11]

,EEID,Job Title,Department,Business Unit,Gender,Ethnicity,Age,Hire Date,Annual Salary,Bonus %,Country,City,Exit Date
0,E93810,Technical Architect,IT,Speciality Products,Male,Asian,30,30-11-2016,143105.97,0.20,United States,Miami,NaN
1,E13905,Technical Architect,Finance,Manufacturing,Male,Asian,63,12-12-1998,138185.50,0.15,Canada,Vancouver,NaN
2,E10851,Director,Marketing,Corporate,Female,Caucasian,31,04-01-1996,70143.93,0.10,United States,New York,NaN
3,E57052,Account Representative,Operations,Speciality Products,Male,Hispanic,56,22-05-2020,57475.66,0.15,United States,Miami,23-09-2022
4,E92397,Account Representative,Operations,Manufacturing,Male,Black,64,29-06-2003,71905.76,0.10,United States,Seattle,NaN
5,E59823,Sr. Analyst,HR,Speciality Products,Male,Caucasian,44,02-10-2002,69330.98,0.10,UK,London,NaN
6,E32431,Computer Systems Manager,Finance,Corporate,Female,Caucasian,62,28-11-1999,136342.67,0.05,UK,Manchester,NaN
7,E17331,Computer Systems Manager,IT,Speciality Products,Female,Caucasian,26,20-03-2020,69537.60,0.20,UK,Manchester,01-02-2021
8,E75435,Manager,Marketing,Corporate,Male,Caucasian,30,08-03-2018,74527.85,0.20,Germany,Munich,NaN
9,E66155,Manager,Sales,Manufacturing,Male,Hispanic,27,11-05-2020,145809.50,0.00,Canada,Toronto,NaN
10,E65333,Technical Architect,HR,Corporate,Female,Caucasian,57,18-09-2013,160509.16,0.00,UK,London,NaN

In [21]:
df["Bonus Amount"] = df["Annual Salary"] * 0.2

In [22]:
df

,EEID,Job Title,Department,Business Unit,Gender,Ethnicity,Age,Hire Date,Annual Salary,Bonus %,Country,City,Exit Date,Bonus Amount
0,E93810,Technical Architect,IT,Speciality Products,Male,Asian,30,30-11-2016,143105.97,0.20,United States,Miami,NaN,28621.194
1,E13905,Technical Architect,Finance,Manufacturing,Male,Asian,63,12-12-1998,138185.50,0.15,Canada,Vancouver,NaN,27637.100
2,E10851,Director,Marketing,Corporate,Female,Caucasian,31,04-01-1996,70143.93,0.10,United States,New York,NaN,14028.786
3,E57052,Account Representative,Operations,Speciality Products,Male,Hispanic,56,22-05-2020,57475.66,0.15,United States,Miami,23-09-2022,11495.132
4,E92397,Account Representative,Operations,Manufacturing,Male,Black,64,29-06-2003,71905.76,0.10,United States,Seattle,NaN,14381.152
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,E94465,Analyst,HR,Manufacturing,Male,Asian,61,22-01-2008,76127.39,0.10,India,Mumbai,NaN,15225.478
496,E97186,Account Representative,Sales,Corporate,Female,Black,26,16-03-2018,106546.81,0.10,India,Bangalore,NaN,21309.362
497,E46996,Account Representative,Operations,Manufacturing,Male,Hispanic,28,12-08-2020,85621.76,0.00,Australia,Melbourne,NaN,17124.352
498,E62535,Manager,Finance,Manufacturing,Male,Hispanic,46,29-01-2001,49248.39,0.05,Australia,Melbourne,NaN,9849.678
499,E67062,Account Representative,Operations,Manufacturing,Male,Black,58,07-02-2016,157144.75,0.00,Germany,Munich,NaN,31428.950

In [23]:
df["Total Salary"] = df["Annual Salary"] + df["Bonus Amount"]

In [24]:
df

,EEID,Job Title,Department,Business Unit,Gender,Ethnicity,Age,Hire Date,Annual Salary,Bonus %,Country,City,Exit Date,Bonus Amount,Total Salary
0,E93810,Technical Architect,IT,Speciality Products,Male,Asian,30,30-11-2016,143105.97,0.20,United States,Miami,NaN,28621.194,171727.164
1,E13905,Technical Architect,Finance,Manufacturing,Male,Asian,63,12-12-1998,138185.50,0.15,Canada,Vancouver,NaN,27637.100,165822.600
2,E10851,Director,Marketing,Corporate,Female,Caucasian,31,04-01-1996,70143.93,0.10,United States,New York,NaN,14028.786,84172.716
3,E57052,Account Representative,Operations,Speciality Products,Male,Hispanic,56,22-05-2020,57475.66,0.15,United States,Miami,23-09-2022,11495.132,68970.792
4,E92397,Account Representative,Operations,Manufacturing,Male,Black,64,29-06-2003,71905.76,0.10,United States,Seattle,NaN,14381.152,86286.912
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,E94465,Analyst,HR,Manufacturing,Male,Asian,61,22-01-2008,76127.39,0.10,India,Mumbai,NaN,15225.478,91352.868
496,E97186,Account Representative,Sales,Corporate,Female,Black,26,16-03-2018,106546.81,0.10,India,Bangalore,NaN,21309.362,127856.172
497,E46996,Account Representative,Operations,Manufacturing,Male,Hispanic,28,12-08-2020,85621.76,0.00,Australia,Melbourne,NaN,17124.352,102746.112
498,E62535,Manager,Finance,Manufacturing,Male,Hispanic,46,29-01-2001,49248.39,0.05,Australia,Melbourne,NaN,9849.678,59098.068
499,E67062,Account Representative,Operations,Manufacturing,Male,Black,58,07-02-2016,157144.75,0.00,Germany,Munich,NaN,31428.950,188573.700

In [ ]:
df.sort_values(by="Department", ascending=True, inplace = True)

In [26]:
df

,EEID,Job Title,Department,Business Unit,Gender,Ethnicity,Age,Hire Date,Annual Salary,Bonus %,Country,City,Exit Date,Bonus Amount,Total Salary
0,E93810,Technical Architect,IT,Speciality Products,Male,Asian,30,30-11-2016,143105.97,0.20,United States,Miami,NaN,28621.194,171727.164
1,E13905,Technical Architect,Finance,Manufacturing,Male,Asian,63,12-12-1998,138185.50,0.15,Canada,Vancouver,NaN,27637.100,165822.600
2,E10851,Director,Marketing,Corporate,Female,Caucasian,31,04-01-1996,70143.93,0.10,United States,New York,NaN,14028.786,84172.716
3,E57052,Account Representative,Operations,Speciality Products,Male,Hispanic,56,22-05-2020,57475.66,0.15,United States,Miami,23-09-2022,11495.132,68970.792
4,E92397,Account Representative,Operations,Manufacturing,Male,Black,64,29-06-2003,71905.76,0.10,United States,Seattle,NaN,14381.152,86286.912
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,E94465,Analyst,HR,Manufacturing,Male,Asian,61,22-01-2008,76127.39,0.10,India,Mumbai,NaN,15225.478,91352.868
496,E97186,Account Representative,Sales,Corporate,Female,Black,26,16-03-2018,106546.81,0.10,India,Bangalore,NaN,21309.362,127856.172
497,E46996,Account Representative,Operations,Manufacturing,Male,Hispanic,28,12-08-2020,85621.76,0.00,Australia,Melbourne,NaN,17124.352,102746.112
498,E62535,Manager,Finance,Manufacturing,Male,Hispanic,46,29-01-2001,49248.39,0.05,Australia,Melbourne,NaN,9849.678,59098.068
499,E67062,Account Representative,Operations,Manufacturing,Male,Black,58,07-02-2016,157144.75,0.00,Germany,Munich,NaN,31428.950,188573.700

In [27]:
df.head(5)

,EEID,Job Title,Department,Business Unit,Gender,Ethnicity,Age,Hire Date,Annual Salary,Bonus %,Country,City,Exit Date,Bonus Amount,Total Salary
0,E93810,Technical Architect,IT,Speciality Products,Male,Asian,30,30-11-2016,143105.97,0.20,United States,Miami,NaN,28621.194,171727.164
1,E13905,Technical Architect,Finance,Manufacturing,Male,Asian,63,12-12-1998,138185.50,0.15,Canada,Vancouver,NaN,27637.100,165822.600
2,E10851,Director,Marketing,Corporate,Female,Caucasian,31,04-01-1996,70143.93,0.10,United States,New York,NaN,14028.786,84172.716
3,E57052,Account Representative,Operations,Speciality Products,Male,Hispanic,56,22-05-2020,57475.66,0.15,United States,Miami,23-09-2022,11495.132,68970.792
4,E92397,Account Representative,Operations,Manufacturing,Male,Black,64,29-06-2003,71905.76,0.10,United States,Seattle,NaN,14381.152,86286.912

In [28]:
df.tail(2)

,EEID,Job Title,Department,Business Unit,Gender,Ethnicity,Age,Hire Date,Annual Salary,Bonus %,Country,City,Exit Date,Bonus Amount,Total Salary
498,E62535,Manager,Finance,Manufacturing,Male,Hispanic,46,29-01-2001,49248.39,0.05,Australia,Melbourne,NaN,9849.678,59098.068
499,E67062,Account Representative,Operations,Manufacturing,Male,Black,58,07-02-2016,157144.75,0.00,Germany,Munich,NaN,31428.950,188573.700

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   EEID           500 non-null    object
 1   Job Title      500 non-null    object
 2   Department     500 non-null    object
 3   Business Unit  500 non-null    object
 4   Gender         500 non-null    object
 5   Ethnicity      500 non-null    object
 6   Age            500 non-null    int64
 7   Hire Date      500 non-null    object
 8   Annual Salary  500 non-null    float64
 9   Bonus %        500 non-null    float64
 10  Country        500 non-null    object
 11  City           500 non-null    object
 12  Exit Date      152 non-null    object
 13  Bonus Amount   500 non-null    float64
 14  Total Salary   500 non-null    float64
dtypes: float64(4), int64(1), object(10)
memory usage: 58.7+ KB