In [2]:
import pandas as pd

In [3]:
import numpy as np

In [4]:
sales = pd.read_csv("Book1.csv")

In [5]:
sales

,OrderID,Date,Region,SalesPerson,Product,Quantity,UnitPrice,Discount,TotalAmount,Category
0,101,1/10/2024,North,Rahul Sharma,Laptop,2,55000,0.10,99000,Electronics
1,102,1/12/2024,South,Priya Mehta,Keyboard,5,1200,0.05,5700,Accessories
2,103,1/14/2024,West,Anil Verma,Mouse,10,700,0.00,7000,Accessories
3,104,1/18/2024,East,Riya Patel,Monitor,3,15000,0.10,40500,Electronics
4,105,1/20/2024,North,Rahul Sharma,Laptop,1,55000,0.00,55000,Electronics
5,106,1/22/2024,South,Priya Mehta,Mouse,15,700,0.10,9450,Accessories
6,107,1/25/2024,West,Anil Verma,Monitor,2,15000,0.05,28500,Electronics
7,108,2/1/2024,East,Riya Patel,Laptop,3,55000,0.10,148500,Electronics
8,109,2/3/2024,North,Rahul Sharma,Mouse,20,700,0.10,12600,Accessories
9,110,2/7/2024,South,Priya Mehta,Laptop,2,55000,0.00,110000,Electronics
10,111,2/8/2024,West,Anil Verma,Keyboard,10,1200,0.10,10800,Accessories
11,112,2/9/2024,East,Riya Patel,Monitor,1,15000,0.00,15000,Electronics
12,113,2/15/2024,North,Rahul Sharma,Keyboard,8,1200,0.05,9120,Accessories
13,114,2/16/2024,South,Priya Mehta,Mouse,10,700,0.00,7000,Accessories
14,115,2/17/2024,West,Anil Verma,Laptop,4,55000,0.10,198000,Electronics
15,116,2/20/2024,East,Riya Patel,Keyboard,7,1200,0.05,7980,Accessories
16,117,2/22/2024,North,Rahul Sharma,Monitor,2,15000,0.00,30000,Electronics
17,118,2/25/2024,South,Priya Mehta,Laptop,5,55000,0.10,247500,Electronics
18,119,2/28/2024,West,Anil Verma,Mouse,5,700,0.00,3500,Accessories
19,120,3/1/2024,East,Riya Patel,Keyboard,6,1200,0.10,6480,Accessories

In [6]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   OrderID      20 non-null     int64
 1   Date         20 non-null     object
 2   Region       20 non-null     object
 3   SalesPerson  20 non-null     object
 4   Product      20 non-null     object
 5   Quantity     20 non-null     int64
 6   UnitPrice    20 non-null     int64
 7   Discount     20 non-null     float64
 8   TotalAmount  20 non-null     int64
 9   Category     20 non-null     object
dtypes: float64(1), int64(4), object(5)
memory usage: 1.7+ KB

In [7]:
sales.loc[sales["Discount"] > 0.05, "Discount_Type"] = "High Discount"
sales.loc[sales["Discount"] <= 0.05, "Discount_Type"] = "Low Discount"

In [8]:
sales

,OrderID,Date,Region,SalesPerson,Product,Quantity,UnitPrice,Discount,TotalAmount,Category,Discount_Type
0,101,1/10/2024,North,Rahul Sharma,Laptop,2,55000,0.10,99000,Electronics,High Discount
1,102,1/12/2024,South,Priya Mehta,Keyboard,5,1200,0.05,5700,Accessories,Low Discount
2,103,1/14/2024,West,Anil Verma,Mouse,10,700,0.00,7000,Accessories,Low Discount
3,104,1/18/2024,East,Riya Patel,Monitor,3,15000,0.10,40500,Electronics,High Discount
4,105,1/20/2024,North,Rahul Sharma,Laptop,1,55000,0.00,55000,Electronics,Low Discount
5,106,1/22/2024,South,Priya Mehta,Mouse,15,700,0.10,9450,Accessories,High Discount
6,107,1/25/2024,West,Anil Verma,Monitor,2,15000,0.05,28500,Electronics,Low Discount
7,108,2/1/2024,East,Riya Patel,Laptop,3,55000,0.10,148500,Electronics,High Discount
8,109,2/3/2024,North,Rahul Sharma,Mouse,20,700,0.10,12600,Accessories,High Discount
9,110,2/7/2024,South,Priya Mehta,Laptop,2,55000,0.00,110000,Electronics,Low Discount
10,111,2/8/2024,West,Anil Verma,Keyboard,10,1200,0.10,10800,Accessories,High Discount
11,112,2/9/2024,East,Riya Patel,Monitor,1,15000,0.00,15000,Electronics,Low Discount
12,113,2/15/2024,North,Rahul Sharma,Keyboard,8,1200,0.05,9120,Accessories,Low Discount
13,114,2/16/2024,South,Priya Mehta,Mouse,10,700,0.00,7000,Accessories,Low Discount
14,115,2/17/2024,West,Anil Verma,Laptop,4,55000,0.10,198000,Electronics,High Discount
15,116,2/20/2024,East,Riya Patel,Keyboard,7,1200,0.05,7980,Accessories,Low Discount
16,117,2/22/2024,North,Rahul Sharma,Monitor,2,15000,0.00,30000,Electronics,Low Discount
17,118,2/25/2024,South,Priya Mehta,Laptop,5,55000,0.10,247500,Electronics,High Discount
18,119,2/28/2024,West,Anil Verma,Mouse,5,700,0.00,3500,Accessories,Low Discount
19,120,3/1/2024,East,Riya Patel,Keyboard,6,1200,0.10,6480,Accessories,High Discount

In [9]:
sales["Quantity"].sum()

np.int64(121)

In [10]:
product_sales = sales.groupby("Product")["TotalAmount"].sum()

In [11]:
product_sales

Product
Keyboard     40080
Laptop      858000
Monitor     114000
Mouse        39550
Name: TotalAmount, dtype: int64

In [12]:
pivots = pd.pivot_table(sales,
                        values = "TotalAmount",
                        index = "Region",
                        columns = "Product",
                        aggfunc = "sum")

In [13]:
pivots

Product  Keyboard    Laptop  Monitor    Mouse
Region
East      14460.0  148500.0  55500.0      NaN
North      9120.0  154000.0  30000.0  12600.0
South      5700.0  357500.0      NaN  16450.0
West      10800.0  198000.0  28500.0  10500.0

In [14]:
pd.crosstab(sales['Region'], sales['Category'])

Category  Accessories  Electronics
Region
East                2            3
North               2            3
South               3            2
West                3            2

In [15]:
sales.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
dtype: bool

In [16]:
sales.drop_duplicates(inplace = True)

In [17]:
sales

,OrderID,Date,Region,SalesPerson,Product,Quantity,UnitPrice,Discount,TotalAmount,Category,Discount_Type
0,101,1/10/2024,North,Rahul Sharma,Laptop,2,55000,0.10,99000,Electronics,High Discount
1,102,1/12/2024,South,Priya Mehta,Keyboard,5,1200,0.05,5700,Accessories,Low Discount
2,103,1/14/2024,West,Anil Verma,Mouse,10,700,0.00,7000,Accessories,Low Discount
3,104,1/18/2024,East,Riya Patel,Monitor,3,15000,0.10,40500,Electronics,High Discount
4,105,1/20/2024,North,Rahul Sharma,Laptop,1,55000,0.00,55000,Electronics,Low Discount
5,106,1/22/2024,South,Priya Mehta,Mouse,15,700,0.10,9450,Accessories,High Discount
6,107,1/25/2024,West,Anil Verma,Monitor,2,15000,0.05,28500,Electronics,Low Discount
7,108,2/1/2024,East,Riya Patel,Laptop,3,55000,0.10,148500,Electronics,High Discount
8,109,2/3/2024,North,Rahul Sharma,Mouse,20,700,0.10,12600,Accessories,High Discount
9,110,2/7/2024,South,Priya Mehta,Laptop,2,55000,0.00,110000,Electronics,Low Discount
10,111,2/8/2024,West,Anil Verma,Keyboard,10,1200,0.10,10800,Accessories,High Discount
11,112,2/9/2024,East,Riya Patel,Monitor,1,15000,0.00,15000,Electronics,Low Discount
12,113,2/15/2024,North,Rahul Sharma,Keyboard,8,1200,0.05,9120,Accessories,Low Discount
13,114,2/16/2024,South,Priya Mehta,Mouse,10,700,0.00,7000,Accessories,Low Discount
14,115,2/17/2024,West,Anil Verma,Laptop,4,55000,0.10,198000,Electronics,High Discount
15,116,2/20/2024,East,Riya Patel,Keyboard,7,1200,0.05,7980,Accessories,Low Discount
16,117,2/22/2024,North,Rahul Sharma,Monitor,2,15000,0.00,30000,Electronics,Low Discount
17,118,2/25/2024,South,Priya Mehta,Laptop,5,55000,0.10,247500,Electronics,High Discount
18,119,2/28/2024,West,Anil Verma,Mouse,5,700,0.00,3500,Accessories,Low Discount
19,120,3/1/2024,East,Riya Patel,Keyboard,6,1200,0.10,6480,Accessories,High Discount

In [18]:
data = {
    "EmployeeID": [101, 102, 103, 104, 105],
    "Name": ["Rahul", "Priya", "Amit", "Sneha", "Karan"],
    "Department": ["Sales", "HR", "IT", np.nan, "Marketing"],
    "Salary": [50000, np.nan, 65000, 48000, np.nan],
    "Experience": [3, 5, np.nan, 2, 4]
}

In [19]:
df = pd.DataFrame(data)

In [20]:
df

   EmployeeID   Name Department   Salary  Experience
0         101  Rahul      Sales  50000.0         3.0
1         102  Priya         HR      NaN         5.0
2         103   Amit         IT  65000.0         NaN
3         104  Sneha        NaN  48000.0         2.0
4         105  Karan  Marketing      NaN         4.0

In [21]:
df.isnull()

   EmployeeID   Name  Department  Salary  Experience
0       False  False       False   False       False
1       False  False       False    True       False
2       False  False       False   False        True
3       False  False        True   False       False
4       False  False       False    True       False

In [22]:
df.notnull()

   EmployeeID  Name  Department  Salary  Experience
0        True  True        True    True        True
1        True  True        True   False        True
2        True  True        True    True       False
3        True  True       False    True        True
4        True  True        True   False        True

In [23]:
df.isnull().sum()

EmployeeID    0
Name          0
Department    1
Salary        2
Experience    1
dtype: int64

In [24]:
df.count()

EmployeeID    5
Name          5
Department    4
Salary        3
Experience    4
dtype: int64

In [25]:
df.count(axis = 1)

0    5
1    4
2    4
3    4
4    4
dtype: int64

In [26]:
df.dropna()

   EmployeeID   Name Department   Salary  Experience
0         101  Rahul      Sales  50000.0         3.0

In [27]:
df.dropna(axis = 1)

   EmployeeID   Name
0         101  Rahul
1         102  Priya
2         103   Amit
3         104  Sneha
4         105  Karan

In [28]:
df.dropna(thresh = 3)

   EmployeeID   Name Department   Salary  Experience
0         101  Rahul      Sales  50000.0         3.0
1         102  Priya         HR      NaN         5.0
2         103   Amit         IT  65000.0         NaN
3         104  Sneha        NaN  48000.0         2.0
4         105  Karan  Marketing      NaN         4.0

In [29]:
df.fillna(0)

   EmployeeID   Name Department   Salary  Experience
0         101  Rahul      Sales  50000.0         3.0
1         102  Priya         HR      0.0         5.0
2         103   Amit         IT  65000.0         0.0
3         104  Sneha          0  48000.0         2.0
4         105  Karan  Marketing      0.0         4.0

In [30]:
df["Salary"].fillna(df["Salary"].mean(), inplace = True)

C:\Users\juhim\AppData\Local\Temp\ipykernel_19420\1868925770.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Salary"].fillna(df["Salary"].mean(), inplace = True)

In [31]:
df

   EmployeeID   Name Department        Salary  Experience
0         101  Rahul      Sales  50000.000000         3.0
1         102  Priya         HR  54333.333333         5.0
2         103   Amit         IT  65000.000000         NaN
3         104  Sneha        NaN  48000.000000         2.0
4         105  Karan  Marketing  54333.333333         4.0

In [32]:
df.fillna(method="ffill")

C:\Users\juhim\AppData\Local\Temp\ipykernel_19420\3944122520.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill")

   EmployeeID   Name Department        Salary  Experience
0         101  Rahul      Sales  50000.000000         3.0
1         102  Priya         HR  54333.333333         5.0
2         103   Amit         IT  65000.000000         5.0
3         104  Sneha         IT  48000.000000         2.0
4         105  Karan  Marketing  54333.333333         4.0

In [33]:
df.fillna(method="bfill")

C:\Users\juhim\AppData\Local\Temp\ipykernel_19420\3896554658.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="bfill")

   EmployeeID   Name Department        Salary  Experience
0         101  Rahul      Sales  50000.000000         3.0
1         102  Priya         HR  54333.333333         5.0
2         103   Amit         IT  65000.000000         2.0
3         104  Sneha  Marketing  48000.000000         2.0
4         105  Karan  Marketing  54333.333333         4.0

In [34]:
df.ffill()

   EmployeeID   Name Department        Salary  Experience
0         101  Rahul      Sales  50000.000000         3.0
1         102  Priya         HR  54333.333333         5.0
2         103   Amit         IT  65000.000000         5.0
3         104  Sneha         IT  48000.000000         2.0
4         105  Karan  Marketing  54333.333333         4.0

In [35]:
df.bfill()

   EmployeeID   Name Department        Salary  Experience
0         101  Rahul      Sales  50000.000000         3.0
1         102  Priya         HR  54333.333333         5.0
2         103   Amit         IT  65000.000000         2.0
3         104  Sneha  Marketing  48000.000000         2.0
4         105  Karan  Marketing  54333.333333         4.0